//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SintecromNet.ProductosWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="https://webservice.ternium.com.ar/", ConfigurationName="ProductosWS.CatalogSoap")]
    public interface CatalogSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el mensaje GetCatalogRequest tiene encabezados.
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.ternium.com.ar/GetCatalog", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        SintecromNet.ProductosWS.GetCatalogResponse GetCatalog(SintecromNet.ProductosWS.GetCatalogRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="https://webservice.ternium.com.ar/GetCatalog", ReplyAction="*")]
        System.Threading.Tasks.Task<SintecromNet.ProductosWS.GetCatalogResponse> GetCatalogAsync(SintecromNet.ProductosWS.GetCatalogRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.ternium.com.ar/")]
    public partial class Authentication : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("userName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.ternium.com.ar/")]
    public partial class Product : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string productIdField;
        
        private string familyIdField;
        
        private string proIdField;
        
        private string productDescField;
        
        private string descShapeField;
        
        private string packingField;
        
        private string minWeightField;
        
        private string maxWeightField;
        
        private float minBatchField;
        
        private float moduleField;
        
        private string customerItemField;
        
        private string sizeField;
        
        private string sizeTypeField;
        
        private float thicknessField;
        
        private string thicknessUnitField;
        
        private float wideField;
        
        private string wideUnitField;
        
        private float lengthField;
        
        private string lengthUnitField;
        
        private string finalUseIdField;
        
        private string descFinalUseField;
        
        private string descPackingField;
        
        private string solderingMarkIdField;
        
        private string descSolderingMarkField;
        
        private string descFamilyField;
        
        private string descDegreeField;
        
        private string shapeIdField;
        
        private string classIdField;
        
        private string descClassField;
        
        private string enabledFromDateField;
        
        private string disabledFromDateField;
        
        private string customerProductIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string productId {
            get {
                return this.productIdField;
            }
            set {
                this.productIdField = value;
                this.RaisePropertyChanged("productId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string familyId {
            get {
                return this.familyIdField;
            }
            set {
                this.familyIdField = value;
                this.RaisePropertyChanged("familyId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string proId {
            get {
                return this.proIdField;
            }
            set {
                this.proIdField = value;
                this.RaisePropertyChanged("proId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string productDesc {
            get {
                return this.productDescField;
            }
            set {
                this.productDescField = value;
                this.RaisePropertyChanged("productDesc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string descShape {
            get {
                return this.descShapeField;
            }
            set {
                this.descShapeField = value;
                this.RaisePropertyChanged("descShape");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string packing {
            get {
                return this.packingField;
            }
            set {
                this.packingField = value;
                this.RaisePropertyChanged("packing");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string minWeight {
            get {
                return this.minWeightField;
            }
            set {
                this.minWeightField = value;
                this.RaisePropertyChanged("minWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string maxWeight {
            get {
                return this.maxWeightField;
            }
            set {
                this.maxWeightField = value;
                this.RaisePropertyChanged("maxWeight");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public float minBatch {
            get {
                return this.minBatchField;
            }
            set {
                this.minBatchField = value;
                this.RaisePropertyChanged("minBatch");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public float module {
            get {
                return this.moduleField;
            }
            set {
                this.moduleField = value;
                this.RaisePropertyChanged("module");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string customerItem {
            get {
                return this.customerItemField;
            }
            set {
                this.customerItemField = value;
                this.RaisePropertyChanged("customerItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string sizeType {
            get {
                return this.sizeTypeField;
            }
            set {
                this.sizeTypeField = value;
                this.RaisePropertyChanged("sizeType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public float thickness {
            get {
                return this.thicknessField;
            }
            set {
                this.thicknessField = value;
                this.RaisePropertyChanged("thickness");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string thicknessUnit {
            get {
                return this.thicknessUnitField;
            }
            set {
                this.thicknessUnitField = value;
                this.RaisePropertyChanged("thicknessUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public float wide {
            get {
                return this.wideField;
            }
            set {
                this.wideField = value;
                this.RaisePropertyChanged("wide");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string wideUnit {
            get {
                return this.wideUnitField;
            }
            set {
                this.wideUnitField = value;
                this.RaisePropertyChanged("wideUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public float length {
            get {
                return this.lengthField;
            }
            set {
                this.lengthField = value;
                this.RaisePropertyChanged("length");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string lengthUnit {
            get {
                return this.lengthUnitField;
            }
            set {
                this.lengthUnitField = value;
                this.RaisePropertyChanged("lengthUnit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string finalUseId {
            get {
                return this.finalUseIdField;
            }
            set {
                this.finalUseIdField = value;
                this.RaisePropertyChanged("finalUseId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string descFinalUse {
            get {
                return this.descFinalUseField;
            }
            set {
                this.descFinalUseField = value;
                this.RaisePropertyChanged("descFinalUse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string descPacking {
            get {
                return this.descPackingField;
            }
            set {
                this.descPackingField = value;
                this.RaisePropertyChanged("descPacking");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string solderingMarkId {
            get {
                return this.solderingMarkIdField;
            }
            set {
                this.solderingMarkIdField = value;
                this.RaisePropertyChanged("solderingMarkId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string descSolderingMark {
            get {
                return this.descSolderingMarkField;
            }
            set {
                this.descSolderingMarkField = value;
                this.RaisePropertyChanged("descSolderingMark");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string descFamily {
            get {
                return this.descFamilyField;
            }
            set {
                this.descFamilyField = value;
                this.RaisePropertyChanged("descFamily");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string descDegree {
            get {
                return this.descDegreeField;
            }
            set {
                this.descDegreeField = value;
                this.RaisePropertyChanged("descDegree");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string shapeId {
            get {
                return this.shapeIdField;
            }
            set {
                this.shapeIdField = value;
                this.RaisePropertyChanged("shapeId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string classId {
            get {
                return this.classIdField;
            }
            set {
                this.classIdField = value;
                this.RaisePropertyChanged("classId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string descClass {
            get {
                return this.descClassField;
            }
            set {
                this.descClassField = value;
                this.RaisePropertyChanged("descClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string enabledFromDate {
            get {
                return this.enabledFromDateField;
            }
            set {
                this.enabledFromDateField = value;
                this.RaisePropertyChanged("enabledFromDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string disabledFromDate {
            get {
                return this.disabledFromDateField;
            }
            set {
                this.disabledFromDateField = value;
                this.RaisePropertyChanged("disabledFromDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string customerProductId {
            get {
                return this.customerProductIdField;
            }
            set {
                this.customerProductIdField = value;
                this.RaisePropertyChanged("customerProductId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://webservice.ternium.com.ar/")]
    public partial class Catalog : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Product[] productsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public Product[] products {
            get {
                return this.productsField;
            }
            set {
                this.productsField = value;
                this.RaisePropertyChanged("products");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCatalog", WrapperNamespace="https://webservice.ternium.com.ar/", IsWrapped=true)]
    public partial class GetCatalogRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="https://webservice.ternium.com.ar/")]
        public SintecromNet.ProductosWS.Authentication Authentication;
        
        public GetCatalogRequest() {
        }
        
        public GetCatalogRequest(SintecromNet.ProductosWS.Authentication Authentication) {
            this.Authentication = Authentication;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCatalogResponse", WrapperNamespace="https://webservice.ternium.com.ar/", IsWrapped=true)]
    public partial class GetCatalogResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="https://webservice.ternium.com.ar/", Order=0)]
        public SintecromNet.ProductosWS.Catalog GetCatalogResult;
        
        public GetCatalogResponse() {
        }
        
        public GetCatalogResponse(SintecromNet.ProductosWS.Catalog GetCatalogResult) {
            this.GetCatalogResult = GetCatalogResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CatalogSoapChannel : SintecromNet.ProductosWS.CatalogSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatalogSoapClient : System.ServiceModel.ClientBase<SintecromNet.ProductosWS.CatalogSoap>, SintecromNet.ProductosWS.CatalogSoap {
        
        public CatalogSoapClient() {
        }
        
        public CatalogSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatalogSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatalogSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SintecromNet.ProductosWS.GetCatalogResponse SintecromNet.ProductosWS.CatalogSoap.GetCatalog(SintecromNet.ProductosWS.GetCatalogRequest request) {
            return base.Channel.GetCatalog(request);
        }
        
        public SintecromNet.ProductosWS.Catalog GetCatalog(SintecromNet.ProductosWS.Authentication Authentication) {
            SintecromNet.ProductosWS.GetCatalogRequest inValue = new SintecromNet.ProductosWS.GetCatalogRequest();
            inValue.Authentication = Authentication;
            SintecromNet.ProductosWS.GetCatalogResponse retVal = ((SintecromNet.ProductosWS.CatalogSoap)(this)).GetCatalog(inValue);
            return retVal.GetCatalogResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SintecromNet.ProductosWS.GetCatalogResponse> SintecromNet.ProductosWS.CatalogSoap.GetCatalogAsync(SintecromNet.ProductosWS.GetCatalogRequest request) {
            return base.Channel.GetCatalogAsync(request);
        }
        
        public System.Threading.Tasks.Task<SintecromNet.ProductosWS.GetCatalogResponse> GetCatalogAsync(SintecromNet.ProductosWS.Authentication Authentication) {
            SintecromNet.ProductosWS.GetCatalogRequest inValue = new SintecromNet.ProductosWS.GetCatalogRequest();
            inValue.Authentication = Authentication;
            return ((SintecromNet.ProductosWS.CatalogSoap)(this)).GetCatalogAsync(inValue);
        }
    }
}
